# -*- coding: utf-8 -*-
"""final assessment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L4SabuhYvV29Nv6xWilUhi7O_Zxx8UxN

## PERFECT NUMBER
"""

n=int(input("enter a number"))
sum=0
for i in range(1,n):
  if n%i==0:
    sum+=i
print("sum=",sum)
if(sum==n):
  print("Perfect number")
else:
  print("Not a perfect number")

